### ISSUE TITLE
The new note is not automatically showed up after click the add button

### ISSUE THREAD

**Issue by gaomc66** [SaltyNote/saltynote-chrome-extension#8]
After added a new page note, the note will not auto shown up. And since there is no refresh button, user needs to close the SaltyNode page and reopen it to see the latest added note.

**Comment by zhouhao** [comment]
First insight: this can be fixed with [event bus](https://andrejsabrickis.medium.com/https-medium-com-andrejsabrickis-create-simple-eventbus-to-communicate-between-vue-js-components-cdc11cd59860).

We can use event bus to emit an event, then inside event listener, we can attach the new note to the side bar list..


It will also be good to add a refresh button somewhere in the UI.

**Comment by zhouhao** [comment]
Sorry, the event bus solution does not work out for this. We need to fetch all notes from server again for that page. As the note ID is generated in server side.

**Comment by zhouhao** [comment]
fixed
